name: "Release Combined Java Lambda Layer"

on:
  push:
    tags:
      - combined-layer-java/**

permissions:
  contents: read

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create Release
        run: gh release create ${{ github.ref_name }} --draft --title ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-combined-layer:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: actions/setup-go@v5
        with:
          go-version-file: collector/go.mod

      - name: Build Combined Layer
        run: |
          cd java
          ARCHITECTURE=${{ matrix.architecture }} ./build-combined.sh
        env:
          ARCHITECTURE: ${{ matrix.architecture }}

      - uses: actions/upload-artifact@v4
        name: Save assembled combined layer to build
        with:
          name: otel-java-extension-layer-${{ matrix.architecture }}.zip
          path: java/build/otel-java-extension-layer-${{ matrix.architecture }}.zip
          
      - name: Add Binary to Release
        run: |
          gh release upload ${{github.ref_name}} java/build/otel-java-extension-layer-${{ matrix.architecture }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-combined-layer:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/layer-publish.yml
    needs: build-combined-layer
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
        aws_region:
          - 'us-east-1'
          - 'us-east-2'
          - 'us-west-1'
          - 'us-west-2'
          - 'eu-central-1'
          - 'eu-central-2'
          - 'eu-north-1'
          - 'eu-west-1'
          - 'eu-west-2'
          - 'eu-west-3'
          - 'eu-south-1'
          - 'eu-south-2'
          - 'sa-east-1'
          - 'ap-northeast-1'
          - 'ap-northeast-2'
          - 'ap-northeast-3'
          - 'ap-south-1'
          - 'ap-south-2'
          - 'ap-southeast-1'
          - 'ap-southeast-2'
          - 'ap-southeast-3'
          - 'ap-southeast-4'
          - 'ap-east-1'
          - 'ca-central-1'
          - 'ca-west-1'
          - 'af-south-1'
          - 'me-south-1'
          - 'me-central-1'
          - 'il-central-1'
    with:
      artifact-name: otel-java-extension-layer-${{ matrix.architecture }}.zip
      layer-name: otel-java-extension
      component-version: "combined"
      architecture: ${{ matrix.architecture }}
      runtimes: java11 java17 java21
      release-group: prod
      aws_region: ${{ matrix.aws_region }}
    secrets: inherit