name: "Release Combined Python Lambda Layer"

on:
  push:
    tags:
      - combined-layer-python/**

permissions:
  contents: read

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Create Release
        run: gh release create ${{ github.ref_name }} --draft --title ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-combined-layer:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: collector/go.mod

      - name: Build Combined Layer
        run: |
          cd python/src
          ARCHITECTURE=${{ matrix.architecture }} ./build-combined.sh
        env:
          ARCHITECTURE: ${{ matrix.architecture }}

      - name: Rename zip file for architecture
        run: |
          mv build/otel-python-extension-layer.zip build/otel-python-extension-layer-${{ matrix.architecture }}.zip
        working-directory: python/src

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        name: Save assembled combined layer to build
        with:
          name: otel-python-extension-layer-${{ matrix.architecture }}.zip
          path: python/src/build/otel-python-extension-layer-${{ matrix.architecture }}.zip
          
      - name: Add Binary to Release
        run: |
          gh release upload ${{github.ref_name}} python/src/build/otel-python-extension-layer-${{ matrix.architecture }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-combined-layer:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/layer-publish.yml
    needs: build-combined-layer
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
        aws_region:
          - ap-northeast-1
          - ap-northeast-2
          - ap-south-1
          - ap-southeast-1
          - ap-southeast-2
          - ca-central-1
          - eu-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - sa-east-1
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
    with:
      artifact-name: otel-python-extension-layer-${{ matrix.architecture }}.zip
      layer-name: otel-python-extension
      component-version: "combined"
      architecture: ${{ matrix.architecture }}
      runtimes: python3.9 python3.10 python3.11 python3.12 python3.13
      release-group: prod
      aws_region: ${{ matrix.aws_region }}
    secrets: inherit